---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: myAccount
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: myBinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: frontend-developer
subjects:
- kind: ServiceAccount
  name: myAccount
---
apiVersion: apps/v1
kind: Deployment
metadata:
 name: mavenappdeployment
spec:
 replicas: 2
 strategy: 
    type: Recreate
 selector: 
   matchLabels: 
     app: mavenapp
 template:
  metadata:
   name: mavenapppod
   labels:
     app: mavenapp	 
  spec:
    serviceAccountName: myAccount
    containers:
    - name: mavenappcontainer
      image: yogeshac/maven_app
      ports:
      - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
 name: mavenappsvc
spec:
  type: LoadBalancer
  selector:
   app: mavenapp
  ports:
   - port: 80
     targetPort: 8080
...
